name: CI
on:
  pull_request:
    paths:
      - white-paper.md
      - metadata.yml
      - img/*
      - .github/workflows/cd.yml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date=$(date '+%Y%m%d')
          echo "- \fancyfoot[L]{WIP-rc+$date}" >> metadata.yml
      - run: |
          sudo apt-get install \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra
          brew install \
            pandoc \
            pandoc-crossref \
            librsvg
      - run: pandoc --version
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: tea.white-paper
          path: tea.white-paper.pdf
